# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: opentelemetry-instrumentation-asyncio
  version: "0.60b1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/opentelemetry_instrumentation_asyncio-${{ version }}.tar.gz
  sha256: 0ddb8ada367c7102662c42433740779a055eace08d65079c86ef65e75d1a66b3

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - opentelemetry-api >=1.14,<2.dev0
    - opentelemetry-instrumentation ==${{ version }}
    - opentelemetry-semantic-conventions ==${{ version }}
    - wrapt >=1.0.0,<2.0.0

tests:
  - python:
      imports:
        - opentelemetry
        - opentelemetry.instrumentation.asyncio
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: OpenTelemetry instrumentation for asyncio
  homepage: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-asyncio
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - conda-forge/opentelemetry-api
